on:
  push:
    branches:
      - main

name: Create and Publish Latest Git

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Repo Name
        id: get_repo_name
        run: |
          # Extract repo name from GITHUB_REPOSITORY variable
          repo_fullname="${{ github.repository }}"
          repo_name="${repo_fullname##*/}"
          echo "REPO_NAME=${repo_name}" >> $GITHUB_ENV

      - name: Get Commit Hash
        id: get_commit_hash
        run: |
          # Extract tag or branch name from GITHUB_REF
          git_hash="$(git rev-parse --short "$GITHUB_SHA")"
          echo "GIT_HASH=${git_hash}" >> $GITHUB_ENV

      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::${REPO_NAME}_$(date +"%Y.%m.%d_%H-%M")_${GIT_HASH}"

      - name: Create Release
        run: |
          echo "Repository Name: $REPO_NAME"
          echo "Tag Name: ${{ steps.tag.outputs.release_tag }}"
          git archive --format zip --prefix="${REPO_NAME}/" --output "${REPO_NAME}-${GIT_HASH}.zip" HEAD
          echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV
          echo "TAG_NAME=${{ steps.tag.outputs.release_tag }}" >> $GITHUB_ENV

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: "${{ env.REPO_NAME }}-${{ env.GIT_HASH }}.zip"
